apiVersion: v1
kind: Service
metadata:
  name: thingsboard-lb-service
  namespace: thingsboard
spec:
  selector:
    app: thingsboard-monolith
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9090
      name: webui
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt
  type: LoadBalancer